// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: session_manager.proto

// Package xnet.sessionmanager.v1 is the FINALIZED v1 wire contract for the
// X-NET Central Session Manager.
//
// This .proto is the single source of truth shared by BOTH sides:
//   - the manager server (this module, github.com/xpanel-cp/xnet-session-manager)
//   - the sing-box node client (the RemoteStore adapter in the sing-box fork).
//
// Because the two live in separate Go modules / repos, the generated Go stubs
// are produced here (via `buf generate`) and regenerated byte-identically into
// the fork from THIS file. The file must stay locked; changes are regenerated
// on both sides together.
//
// v1 ships UNARY RPCs ONLY. Field numbers are kept stable and reserved for
// evolution, and the two planned server-streaming RPCs are declared as
// comments/reservations so they can be added later with NO breaking change to
// the unary contract.
//
// Transport / security note: mTLS is a pure transport-layer concern (gRPC
// channel credentials); enabling it later requires NO change to any message or
// RPC here. HMAC-SHA256 per-node auth is carried in call metadata
// (node_id / timestamp / nonce / signature), not in these messages.
//
// ---------------------------------------------------------------------------
// FORK COPY NOTE (sing-box RemoteStore, Phase 3 / Task 10):
// The package name, messages, fields, field numbers, and service/RPC
// definitions below are BYTE-IDENTICAL to the manager's canonical copy at
//   f:\xnet\session-manager\proto\sessionmanagerv1\session_manager.proto
// so the two modules stay WIRE-COMPATIBLE. The ONLY intentional divergence is
// the `option go_package` line: it points into THIS module
// (github.com/sagernet/sing-box) instead of the manager module, because the
// fork is a separate Go module and cannot share the manager's import path. A
// different Go import path does NOT affect wire compatibility. When the
// contract changes, regenerate BOTH sides from the same definitions.
// ---------------------------------------------------------------------------

package managerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AcquireSessionRequest carries both caps; each is independently disableable
// (0/absent disables that cap). device_key is OPAQUE (node-composed); the
// manager keys on it verbatim.
type AcquireSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	DeviceKey     string                 `protobuf:"bytes,2,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`        // OPAQUE (node-composed); manager keys on it verbatim
	MaxDevices    int32                  `protobuf:"varint,3,opt,name=max_devices,json=maxDevices,proto3" json:"max_devices,omitempty"`    // 0/absent disables the device cap
	MaxSessions   int32                  `protobuf:"varint,4,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"` // 0/absent disables the session cap
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,6,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"` // unique per-connection; idempotency key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionRequest) Reset() {
	*x = AcquireSessionRequest{}
	mi := &file_session_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionRequest) ProtoMessage() {}

func (x *AcquireSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionRequest.ProtoReflect.Descriptor instead.
func (*AcquireSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireSessionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AcquireSessionRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *AcquireSessionRequest) GetMaxDevices() int32 {
	if x != nil {
		return x.MaxDevices
	}
	return 0
}

func (x *AcquireSessionRequest) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *AcquireSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AcquireSessionRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type AcquireSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admitted      bool                   `protobuf:"varint,1,opt,name=admitted,proto3" json:"admitted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // DEVICE_LIMIT_REACHED / SESSION_LIMIT_REACHED / ...
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Ttl           int64                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"` // lease TTL in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionResponse) Reset() {
	*x = AcquireSessionResponse{}
	mi := &file_session_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionResponse) ProtoMessage() {}

func (x *AcquireSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionResponse.ProtoReflect.Descriptor instead.
func (*AcquireSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireSessionResponse) GetAdmitted() bool {
	if x != nil {
		return x.Admitted
	}
	return false
}

func (x *AcquireSessionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AcquireSessionResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AcquireSessionResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// ReleaseSessionRequest frees the slot for lease_id. Idempotent; releasing an
// unknown/expired lease is a no-op success.
type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // owning node (authorization: own-lease rule)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_session_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseSessionRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"` // true if a slot was freed; false if already gone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_session_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseSessionResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

// RenewLeaseRequest renews a batch of leases in one call (heartbeat).
type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       []string               `protobuf:"bytes,1,rep,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // owning node (authorization: own-lease rule)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_session_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{4}
}

func (x *RenewLeaseRequest) GetLeaseId() []string {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *RenewLeaseRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RenewLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         []string               `protobuf:"bytes,1,rep,name=valid,proto3" json:"valid,omitempty"`     // leases still valid (extended)
	Expired       []string               `protobuf:"bytes,2,rep,name=expired,proto3" json:"expired,omitempty"` // leases that were unknown/already expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_session_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{5}
}

func (x *RenewLeaseResponse) GetValid() []string {
	if x != nil {
		return x.Valid
	}
	return nil
}

func (x *RenewLeaseResponse) GetExpired() []string {
	if x != nil {
		return x.Expired
	}
	return nil
}

// GetSessionSnapshotRequest asks for the live device/session view of a user.
type GetSessionSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionSnapshotRequest) Reset() {
	*x = GetSessionSnapshotRequest{}
	mi := &file_session_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionSnapshotRequest) ProtoMessage() {}

func (x *GetSessionSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSessionSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionSnapshotRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetSessionSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Devices       []*Device              `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	Sessions      int32                  `protobuf:"varint,3,opt,name=sessions,proto3" json:"sessions,omitempty"` // total live sessions across devices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionSnapshotResponse) Reset() {
	*x = GetSessionSnapshotResponse{}
	mi := &file_session_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionSnapshotResponse) ProtoMessage() {}

func (x *GetSessionSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSessionSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionSnapshotResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetSessionSnapshotResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetSessionSnapshotResponse) GetSessions() int32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

// Device is an observability projection of one device slot.
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey     string                 `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Connections   int32                  `protobuf:"varint,3,opt,name=connections,proto3" json:"connections,omitempty"`                 // live connections attached to this device slot
	FirstSeen     int64                  `protobuf:"varint,4,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`    // unix millis
	LastActive    int64                  `protobuf:"varint,5,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_session_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{8}
}

func (x *Device) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *Device) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Device) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *Device) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *Device) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

// RevokeSessionRequest is the admin/future control path. device_key is optional
// (empty = revoke all of the user's sessions).
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	DeviceKey     string                 `protobuf:"bytes,2,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"` // optional; empty revokes all of the user's sessions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_session_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeSessionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RevokeSessionRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Freed         int32                  `protobuf:"varint,2,opt,name=freed,proto3" json:"freed,omitempty"` // number of slots freed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_session_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeSessionResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeSessionResponse) GetFreed() int32 {
	if x != nil {
		return x.Freed
	}
	return 0
}

var File_session_manager_proto protoreflect.FileDescriptor

const file_session_manager_proto_rawDesc = "" +
	"\n" +
	"\x15session_manager.proto\x12\x16xnet.sessionmanager.v1\"\xc6\x01\n" +
	"\x15AcquireSessionRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"device_key\x18\x02 \x01(\tR\tdeviceKey\x12\x1f\n" +
	"\vmax_devices\x18\x03 \x01(\x05R\n" +
	"maxDevices\x12!\n" +
	"\fmax_sessions\x18\x04 \x01(\x05R\vmaxSessions\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aconn_id\x18\x06 \x01(\tR\x06connIdJ\x04\b\a\x10\x10\"\x7f\n" +
	"\x16AcquireSessionResponse\x12\x1a\n" +
	"\badmitted\x18\x01 \x01(\bR\badmitted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x03R\x03ttlJ\x04\b\x05\x10\x10\"Q\n" +
	"\x15ReleaseSessionRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeIdJ\x04\b\x03\x10\x10\":\n" +
	"\x16ReleaseSessionResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleasedJ\x04\b\x02\x10\x10\"M\n" +
	"\x11RenewLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x03(\tR\aleaseId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeIdJ\x04\b\x03\x10\x10\"J\n" +
	"\x12RenewLeaseResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x03(\tR\x05valid\x12\x18\n" +
	"\aexpired\x18\x02 \x03(\tR\aexpiredJ\x04\b\x03\x10\x10\"5\n" +
	"\x19GetSessionSnapshotRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04userJ\x04\b\x02\x10\x10\"\x8c\x01\n" +
	"\x1aGetSessionSnapshotResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x128\n" +
	"\adevices\x18\x02 \x03(\v2\x1e.xnet.sessionmanager.v1.DeviceR\adevices\x12\x1a\n" +
	"\bsessions\x18\x03 \x01(\x05R\bsessionsJ\x04\b\x04\x10\x10\"\x9f\x01\n" +
	"\x06Device\x12\x1d\n" +
	"\n" +
	"device_key\x18\x01 \x01(\tR\tdeviceKey\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12 \n" +
	"\vconnections\x18\x03 \x01(\x05R\vconnections\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x04 \x01(\x03R\tfirstSeen\x12\x1f\n" +
	"\vlast_active\x18\x05 \x01(\x03R\n" +
	"lastActiveJ\x04\b\x06\x10\x10\"O\n" +
	"\x14RevokeSessionRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"device_key\x18\x02 \x01(\tR\tdeviceKeyJ\x04\b\x03\x10\x10\"M\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x12\x14\n" +
	"\x05freed\x18\x02 \x01(\x05R\x05freedJ\x04\b\x03\x10\x102\xc2\x04\n" +
	"\x0eSessionManager\x12o\n" +
	"\x0eAcquireSession\x12-.xnet.sessionmanager.v1.AcquireSessionRequest\x1a..xnet.sessionmanager.v1.AcquireSessionResponse\x12o\n" +
	"\x0eReleaseSession\x12-.xnet.sessionmanager.v1.ReleaseSessionRequest\x1a..xnet.sessionmanager.v1.ReleaseSessionResponse\x12c\n" +
	"\n" +
	"RenewLease\x12).xnet.sessionmanager.v1.RenewLeaseRequest\x1a*.xnet.sessionmanager.v1.RenewLeaseResponse\x12{\n" +
	"\x12GetSessionSnapshot\x121.xnet.sessionmanager.v1.GetSessionSnapshotRequest\x1a2.xnet.sessionmanager.v1.GetSessionSnapshotResponse\x12l\n" +
	"\rRevokeSession\x12,.xnet.sessionmanager.v1.RevokeSessionRequest\x1a-.xnet.sessionmanager.v1.RevokeSessionResponseB\\ZZgithub.com/sagernet/sing-box/experimental/sessionadmission/remotestore/managerpb;managerpbb\x06proto3"

var (
	file_session_manager_proto_rawDescOnce sync.Once
	file_session_manager_proto_rawDescData []byte
)

func file_session_manager_proto_rawDescGZIP() []byte {
	file_session_manager_proto_rawDescOnce.Do(func() {
		file_session_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_manager_proto_rawDesc), len(file_session_manager_proto_rawDesc)))
	})
	return file_session_manager_proto_rawDescData
}

var file_session_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_session_manager_proto_goTypes = []any{
	(*AcquireSessionRequest)(nil),      // 0: xnet.sessionmanager.v1.AcquireSessionRequest
	(*AcquireSessionResponse)(nil),     // 1: xnet.sessionmanager.v1.AcquireSessionResponse
	(*ReleaseSessionRequest)(nil),      // 2: xnet.sessionmanager.v1.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil),     // 3: xnet.sessionmanager.v1.ReleaseSessionResponse
	(*RenewLeaseRequest)(nil),          // 4: xnet.sessionmanager.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),         // 5: xnet.sessionmanager.v1.RenewLeaseResponse
	(*GetSessionSnapshotRequest)(nil),  // 6: xnet.sessionmanager.v1.GetSessionSnapshotRequest
	(*GetSessionSnapshotResponse)(nil), // 7: xnet.sessionmanager.v1.GetSessionSnapshotResponse
	(*Device)(nil),                     // 8: xnet.sessionmanager.v1.Device
	(*RevokeSessionRequest)(nil),       // 9: xnet.sessionmanager.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),      // 10: xnet.sessionmanager.v1.RevokeSessionResponse
}
var file_session_manager_proto_depIdxs = []int32{
	8,  // 0: xnet.sessionmanager.v1.GetSessionSnapshotResponse.devices:type_name -> xnet.sessionmanager.v1.Device
	0,  // 1: xnet.sessionmanager.v1.SessionManager.AcquireSession:input_type -> xnet.sessionmanager.v1.AcquireSessionRequest
	2,  // 2: xnet.sessionmanager.v1.SessionManager.ReleaseSession:input_type -> xnet.sessionmanager.v1.ReleaseSessionRequest
	4,  // 3: xnet.sessionmanager.v1.SessionManager.RenewLease:input_type -> xnet.sessionmanager.v1.RenewLeaseRequest
	6,  // 4: xnet.sessionmanager.v1.SessionManager.GetSessionSnapshot:input_type -> xnet.sessionmanager.v1.GetSessionSnapshotRequest
	9,  // 5: xnet.sessionmanager.v1.SessionManager.RevokeSession:input_type -> xnet.sessionmanager.v1.RevokeSessionRequest
	1,  // 6: xnet.sessionmanager.v1.SessionManager.AcquireSession:output_type -> xnet.sessionmanager.v1.AcquireSessionResponse
	3,  // 7: xnet.sessionmanager.v1.SessionManager.ReleaseSession:output_type -> xnet.sessionmanager.v1.ReleaseSessionResponse
	5,  // 8: xnet.sessionmanager.v1.SessionManager.RenewLease:output_type -> xnet.sessionmanager.v1.RenewLeaseResponse
	7,  // 9: xnet.sessionmanager.v1.SessionManager.GetSessionSnapshot:output_type -> xnet.sessionmanager.v1.GetSessionSnapshotResponse
	10, // 10: xnet.sessionmanager.v1.SessionManager.RevokeSession:output_type -> xnet.sessionmanager.v1.RevokeSessionResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_session_manager_proto_init() }
func file_session_manager_proto_init() {
	if File_session_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_manager_proto_rawDesc), len(file_session_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_manager_proto_goTypes,
		DependencyIndexes: file_session_manager_proto_depIdxs,
		MessageInfos:      file_session_manager_proto_msgTypes,
	}.Build()
	File_session_manager_proto = out.File
	file_session_manager_proto_goTypes = nil
	file_session_manager_proto_depIdxs = nil
}
