// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: session_manager.proto

// Package xnet.sessionmanager.v1 is the FINALIZED v1 wire contract for the
// X-NET Central Session Manager.
//
// This .proto is the single source of truth shared by BOTH sides:
//   - the manager server (this module, github.com/xpanel-cp/xnet-session-manager)
//   - the sing-box node client (the RemoteStore adapter in the sing-box fork).
//
// Because the two live in separate Go modules / repos, the generated Go stubs
// are produced here (via `buf generate`) and regenerated byte-identically into
// the fork from THIS file. The file must stay locked; changes are regenerated
// on both sides together.
//
// v1 ships UNARY RPCs ONLY. Field numbers are kept stable and reserved for
// evolution, and the two planned server-streaming RPCs are declared as
// comments/reservations so they can be added later with NO breaking change to
// the unary contract.
//
// Transport / security note: mTLS is a pure transport-layer concern (gRPC
// channel credentials); enabling it later requires NO change to any message or
// RPC here. HMAC-SHA256 per-node auth is carried in call metadata
// (node_id / timestamp / nonce / signature), not in these messages.
//
// ---------------------------------------------------------------------------
// FORK COPY NOTE (sing-box RemoteStore, Phase 3 / Task 10):
// The package name, messages, fields, field numbers, and service/RPC
// definitions below are BYTE-IDENTICAL to the manager's canonical copy at
//   f:\xnet\session-manager\proto\sessionmanagerv1\session_manager.proto
// so the two modules stay WIRE-COMPATIBLE. The ONLY intentional divergence is
// the `option go_package` line: it points into THIS module
// (github.com/sagernet/sing-box) instead of the manager module, because the
// fork is a separate Go module and cannot share the manager's import path. A
// different Go import path does NOT affect wire compatibility. When the
// contract changes, regenerate BOTH sides from the same definitions.
// ---------------------------------------------------------------------------

package managerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionManager_AcquireSession_FullMethodName     = "/xnet.sessionmanager.v1.SessionManager/AcquireSession"
	SessionManager_ReleaseSession_FullMethodName     = "/xnet.sessionmanager.v1.SessionManager/ReleaseSession"
	SessionManager_RenewLease_FullMethodName         = "/xnet.sessionmanager.v1.SessionManager/RenewLease"
	SessionManager_GetSessionSnapshot_FullMethodName = "/xnet.sessionmanager.v1.SessionManager/GetSessionSnapshot"
	SessionManager_RevokeSession_FullMethodName      = "/xnet.sessionmanager.v1.SessionManager/RevokeSession"
	SessionManager_NodeHeartbeat_FullMethodName      = "/xnet.sessionmanager.v1.SessionManager/NodeHeartbeat"
)

// SessionManagerClient is the client API for SessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionManager is the central authority for per-user device and concurrent-
// session limits enforced globally across every X-NET node.
type SessionManagerClient interface {
	// AcquireSession evaluates both caps atomically for the user and admits or
	// rejects one connection. This is the hot admission path (gRPC only).
	AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error)
	// ReleaseSession frees the slot held by a lease. Idempotent.
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	// RenewLease renews a batch of leases (node heartbeat / keepalive) and
	// reports which are still valid and which have expired.
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	// GetSessionSnapshot returns the live device/session view for a user
	// (observability / admin read).
	GetSessionSnapshot(ctx context.Context, in *GetSessionSnapshotRequest, opts ...grpc.CallOption) (*GetSessionSnapshotResponse, error)
	// RevokeSession is an ADMIN/future control operation. Node RPC credentials
	// cannot revoke; the manager denies node callers (PermissionDenied) in v1.
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error)
	// NodeHeartbeat is an OPTIONAL, strictly ADDITIVE liveness signal by which an
	// IDLE node holding zero leases refreshes its last_heartbeat in the manager's
	// NodeRegistry (Requirement 17.3). A node holding leases refreshes its
	// liveness implicitly through RenewLease, so this RPC is only needed while a
	// node has no live leases to renew. It is a NODE-role data-plane op,
	// authenticated exactly like the other node RPCs (HMAC in call metadata).
	NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error)
}

type sessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerClient(cc grpc.ClientConnInterface) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSessionResponse)
	err := c.cc.Invoke(ctx, SessionManager_AcquireSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, SessionManager_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, SessionManager_RenewLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) GetSessionSnapshot(ctx context.Context, in *GetSessionSnapshotRequest, opts ...grpc.CallOption) (*GetSessionSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionSnapshotResponse)
	err := c.cc.Invoke(ctx, SessionManager_GetSessionSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSessionResponse)
	err := c.cc.Invoke(ctx, SessionManager_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHeartbeatResponse)
	err := c.cc.Invoke(ctx, SessionManager_NodeHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServer is the server API for SessionManager service.
// All implementations must embed UnimplementedSessionManagerServer
// for forward compatibility.
//
// SessionManager is the central authority for per-user device and concurrent-
// session limits enforced globally across every X-NET node.
type SessionManagerServer interface {
	// AcquireSession evaluates both caps atomically for the user and admits or
	// rejects one connection. This is the hot admission path (gRPC only).
	AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error)
	// ReleaseSession frees the slot held by a lease. Idempotent.
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	// RenewLease renews a batch of leases (node heartbeat / keepalive) and
	// reports which are still valid and which have expired.
	RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	// GetSessionSnapshot returns the live device/session view for a user
	// (observability / admin read).
	GetSessionSnapshot(context.Context, *GetSessionSnapshotRequest) (*GetSessionSnapshotResponse, error)
	// RevokeSession is an ADMIN/future control operation. Node RPC credentials
	// cannot revoke; the manager denies node callers (PermissionDenied) in v1.
	RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error)
	// NodeHeartbeat is an OPTIONAL, strictly ADDITIVE liveness signal by which an
	// IDLE node holding zero leases refreshes its last_heartbeat in the manager's
	// NodeRegistry (Requirement 17.3). A node holding leases refreshes its
	// liveness implicitly through RenewLease, so this RPC is only needed while a
	// node has no live leases to renew. It is a NODE-role data-plane op,
	// authenticated exactly like the other node RPCs (HMAC in call metadata).
	NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error)
	mustEmbedUnimplementedSessionManagerServer()
}

// UnimplementedSessionManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagerServer struct{}

func (UnimplementedSessionManagerServer) AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireSession not implemented")
}
func (UnimplementedSessionManagerServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedSessionManagerServer) RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedSessionManagerServer) GetSessionSnapshot(context.Context, *GetSessionSnapshotRequest) (*GetSessionSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionSnapshot not implemented")
}
func (UnimplementedSessionManagerServer) RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedSessionManagerServer) NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeHeartbeat not implemented")
}
func (UnimplementedSessionManagerServer) mustEmbedUnimplementedSessionManagerServer() {}
func (UnimplementedSessionManagerServer) testEmbeddedByValue()                        {}

// UnsafeSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServer will
// result in compilation errors.
type UnsafeSessionManagerServer interface {
	mustEmbedUnimplementedSessionManagerServer()
}

func RegisterSessionManagerServer(s grpc.ServiceRegistrar, srv SessionManagerServer) {
	// If the following call panics, it indicates UnimplementedSessionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManager_ServiceDesc, srv)
}

func _SessionManager_AcquireSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).AcquireSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_AcquireSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).AcquireSession(ctx, req.(*AcquireSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_GetSessionSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetSessionSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_GetSessionSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetSessionSnapshot(ctx, req.(*GetSessionSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_NodeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).NodeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_NodeHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).NodeHeartbeat(ctx, req.(*NodeHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManager_ServiceDesc is the grpc.ServiceDesc for SessionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xnet.sessionmanager.v1.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireSession",
			Handler:    _SessionManager_AcquireSession_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _SessionManager_ReleaseSession_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _SessionManager_RenewLease_Handler,
		},
		{
			MethodName: "GetSessionSnapshot",
			Handler:    _SessionManager_GetSessionSnapshot_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _SessionManager_RevokeSession_Handler,
		},
		{
			MethodName: "NodeHeartbeat",
			Handler:    _SessionManager_NodeHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session_manager.proto",
}
